//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Timers;
namespace AssemblyCSharp
{
		public class Timer
		{
		static Timer timerForMoney;
		private int tickAmount = 50;
		private int milisecondsPerTick = 5000;
				public Timer ()
				{
			Start ();

				}
		// Increases the tick amount of money that will be added to the players
		public void increaseTickAmount( int amountToIncreaseBy){
			this.tickAmount += amountToIncreaseBy;
		}
		// Decreases the time inbetween each tick of the timer
		public void increaseTickSpeed(int amountToDecreseBy){
			this.milisecondsPerTick -= amountToDecreseBy;
		}
}

