// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

public class FlockingBehavior : Behavior
{
	public FlockingBehavior (Ant ant)
	{
		this.ant = ant;
	}

	public override Vector2 nextDirection() {
		FlockingCalculator calculator = new FlockingCalculator(ant, getAllyAnts());
		return calculator.nextVelocity() / ant.speed;
	}

	public override Ant antToAttack ()
	{
		return getNearestAnt ();
	}

}

