// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

public class FlockingBehavior : Behavior
{
	FlockingCalculator calculator;

	public FlockingBehavior (Ant ant){
		this.ant = ant;
		this.calculator = new FlockingCalculator2(ant);
	}

	public override Vector2 nextDirection() {
		Ant[] ants = getAllyAnts();
		calculator.setFlocks (ants, getEnemyAnts());
		Vector2 direction = calculator.nextVelocity().normalized;
		float speed = Vector2.Distance(flockCenter(ants), ant.position()) < 0 ? slowestSpeed(ants) : ant.speed;
		return direction * (speed / ant.speed);
	}

	Vector2 flockCenter(Ant[] flock){
		Vector2 flockCenter = Vector2.zero;
		foreach(Ant ant in flock) {
			flockCenter = flockCenter + (Vector2) ant.position();
		}
		return (flockCenter / flock.Length);
	}

	private float slowestSpeed(Ant[] flock){
		Ant slowest = flock[0];
		foreach(Ant a in flock){
			if(a.speed < slowest.speed)
				slowest = a;
		}
		return slowest.speed;
	}

	public override Ant antToAttack (){
		return getNearestAnt ();
	}

}

