// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

public class FlockingBehavior : Behavior
{
	FlockingCalculator calculator;

	public FlockingBehavior (Ant ant)
	{
		this.ant = ant;
		this.calculator = new FlockingCalculator (ant);
	}

	public override Vector2 nextDirection() {
		if (getAllyAnts().Length == 0) {
			Ant antTarget = getNearestAnt ();
			GameObject target = antTarget == null ? ant.enemyHive.gameObject : antTarget.gameObject;
			Vector2 offset = target.transform.position - ant.transform.position;
			float length = Mathf.Sqrt (offset.sqrMagnitude);

			return new Vector2 (offset.x / length, offset.y / length);
		} else {
			calculator.setFlocks (getAllyAnts(), getEnemyAnts());
			return calculator.nextVelocity () / ant.speed;
		}
	}

	public override Ant antToAttack (){
		return getNearestAnt ();
	}

}

