// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using System.Collections;
using System.Linq;


public class ThreatMap : object {
	IEnumerable<Ant> enemies;

	public ThreatMap (IEnumerable<Ant> enemies) {
		this.enemies = enemies;
	}

	public float getThreatLevel(Vector2 position) {
		float threat = 0;
		foreach (Ant enemy in enemies) {
		}
		return threat;
	}
}