// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using System.Collections;
using System.Linq;


public class ThreatMap : object {
	IEnumerable<Ant> enemies;

	public ThreatMap() {
	}

	public Vector2 getTarget(Ant ant, IEnumerable<Ant> enemies) {
		Vector2 current = ant.position();
		Vector2 target = ant.enemyHive.position();

		foreach (Ant enemy in enemies) {
			if (Vector2.Distance(current, enemy.position()) < Vector2.Distance(current, target)) {
				target = enemy.position();
			}
		}


		return target;
	}
}